require("dotenv").config()
const knex = require("../bin/conn")
const Utils = require("../bin/utils")

const TABLE = "products"

const createProductsTable = async () => {
  if (await knex.schema.hasTable(TABLE)) {
    throw new Error(`Table ${TABLE} already exists`)
  }

  return knex.schema.createTable(TABLE, (table) => {
    table.integer("id").primary()
    table.string("brand")
    table.string("model")
    table.string("model_code")
    table.date("released")
    table.string("general_extras")
    table.string("device_category")
    table.string("list_of_additional_features")
    table.float("depth")
    table.float("mass")
    table.string("platform")
    table.string("operating_system")
    table.string("software_extras")
    table.integer("cpu_clock")
    table.string("cpu")
    table.integer("ram_capacity")
    table.integer("non_volatile_memory_capacity")
    table.float("display_diagonal")
    table.string("resolution")
    table.float("pixel_size")
    table.integer("pixel_density")
    table.string("display_type")
    table.string("display_subtype")
    table.string("scratch_resistant_screen")
    table.string("graphical_controller")
    table.string("supported_cellular_bands")
    table.string("supported_cellular_data_links")
    table.string("sim_card_slot")
    table.float("sar")
    table.string("sar_measurement_method")
    table.string("dual_cellular_network_operation")
    table.string("bluetooth")
    table.string("wireless_lan")
    table.string("wireless_services")
    table.string("nfc")
    table.string("camera_placement")
    table.string("camera_image_sensor")
    table.float("image_sensor_pixel_size")
    table.string("camera_resolution")
    table.float("number_of_effective_pixels")
    table.integer("zoom")
    table.integer("digital_zoom")
    table.string("video_recording")
    table.integer("camcorder_frame_rate")
    table.string("flash")
    table.string("camera_extra_functions")
    table.string("aux_camera_image_sensor")
    table.float("aux_camera_number_of_pixels")
    table.string("secondary_camera_placement")
    table.string("secondary_camera_sensor")
    table.float("secondary_image_sensor_pixel_size")
    table.float("secondary_camera_number_of_pixels")
    table.string("secondary_camera_extra_functions")
    table.string("built_in_compass")
    table.string("built_in_accelerometer")
    table.string("built_in_gyroscope")
    table.string("additional_sensors")
    table.string("built_in_barcode_scanner")
    table.string("battery")
    table.string("battery_build")
    table.float("talk_time")
    table.string("wireless_charging")
    table.string("price_currency")
    table.string("image")
    table.string("data_integrity")
    table.string("added")

    // internal
    table.string("url")
    table.timestamps(true, true)

    table.index("brand")
    table.index("model")
    table.index("model_code")
    table.unique("url")
  })
}

if (require.main === module) {
  Utils.log(`Creating ${TABLE} table...`)
  createProductsTable()
    .then(() => {
      Utils.log("DONE")
      return true
    })
    .catch((error) => {
      Utils.log(error)
    })
}
